services:
  pgvector:
    image: 'pgvector/pgvector:pg17'
    environment:
      - 'POSTGRES_DB=my_pg_db'
      - 'POSTGRES_USER=spring'
      - 'POSTGRES_PASSWORD=secret'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'