jasypt:
  encryptor:
    bean: jasyptEncryptorAES
    password: ${JASYPT_ENC_PWD}

spring:
  application:
    name: spring-ai-tutorial
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
      embedding:
        options:
          model: text-embedding-ada-002
#      image:
#        options:
#          model: dall-e-3
#          quality: hd
#          n: 1
#          height: 1024
#          width: 1024
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
        initialize-schema: false
  docker:
    compose:
      enabled: false

  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/my_pg_db
#    username: "spring"
#    password: "secret"

    url: jdbc:postgresql://digitalab.synology.me:6432/dlab_ai_pg
    username: "dlab_ai"
    password: "ENC(2y0jzDpNlnzt/SuW7eZeiUBbPj6YjNYeNuX8qnaNm6J7KOuT3Gn1s5TIQY7PdyQd)"

  # File Upload Settings
  servlet:
    multipart:
      max-file-size: '20MB'
      max-request-size: '20MB'

# Server Configuration
server:
  port: 8080

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs

# Webhook Configuration
webhook:
  url: ${WEBHOOK_URL:}
