spring:
  application:
    name: spring-ai-tutorial
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
  # File Upload Settings
  servlet:
    multipart:
      max-file-size: '20MB'
      max-request-size: '20MB'

# Server Configuration
server:
  port: 8080

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs

# Storm API Configuration
storm:
  api:
    key: ${STORM_API_KEY:demo-key}
  default:
    bucket:
      id: default-bucket

# Webhook Configuration
webhook:
  url: ${WEBHOOK_URL:}
